# Generated by Django 2.0.2 on 2018-06-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20180224_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('DC', 'DC'), ('Marvel', 'Marvel')], max_length=120),
        ),
    ]
