# Generated by Django 2.0.2 on 2018-06-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180612_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='gallery/'),
        ),
    ]
